# Generated by Django 5.1.5 on 2025-01-28 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0002_wasterequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreport',
            old_name='timestamp',
            new_name='report_date',
        ),
        migrations.AddField(
            model_name='userreport',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='report_photos/'),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='bin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='waste.wastebin'),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='report_type',
            field=models.CharField(choices=[('Overflow', 'Overflow'), ('Damage', 'Damage'), ('Odor Issue', 'Odor Issue')], max_length=50),
        ),
        migrations.CreateModel(
            name='CollectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_time', models.DateTimeField()),
                ('collected_by', models.CharField(max_length=100)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.wastebin')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comments', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
